# Generated by Django 4.1.6 on 2023-04-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_orders_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='images',
            field=models.ImageField(null=True, upload_to='user/profile_pic'),
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ImageField(null=True, upload_to='user/profile_pic'),
        ),
    ]
