# Generated by Django 4.1.6 on 2023-04-29 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_subcatagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcatagory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.subcatagory'),
        ),
    ]
