# Generated by Django 4.1.6 on 2023-04-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_orders_name_orders_phoneno_alter_orders_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='location',
            field=models.CharField(default='dd', max_length=255),
            preserve_default=False,
        ),
    ]
