# Generated by Django 4.2.6 on 2023-10-07 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_remove_chapatransaction_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapatransaction',
            name='checkout_url',
        ),
        migrations.RemoveField(
            model_name='chapatransaction',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='chapatransaction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='chapatransaction',
            name='payment_title',
        ),
        migrations.RemoveField(
            model_name='chapatransaction',
            name='status',
        ),
    ]
