# Generated by Django 4.2.6 on 2023-10-07 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_chapatransaction_headline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChapaTransaction',
        ),
    ]
