# Generated by Django 4.2.6 on 2023-10-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_delete_chapatransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='ETB', max_length=25)),
                ('payment_title', models.CharField(default='Payment', max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('created', 'CREATED'), ('pending', 'PENDING'), ('success', 'SUCCESS'), ('failed', 'FAILED')], default='created', max_length=50)),
                ('checkout_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chapa Transaction',
                'verbose_name_plural': 'Chapa Transactions',
            },
        ),
    ]
