# Generated by Django 4.2.6 on 2023-10-07 23:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_chapatransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapatransaction',
            name='amount',
            field=models.FloatField(default=66),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapatransaction',
            name='email',
            field=models.EmailField(default='JJ', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapatransaction',
            name='first_name',
            field=models.CharField(default='K', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapatransaction',
            name='last_name',
            field=models.CharField(default='KKK', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapatransaction',
            name='phone_number',
            field=models.CharField(default=667777899, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapatransaction',
            name='response_dump',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='chapatransaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
