# Generated by Django 4.2.6 on 2023-10-08 20:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_orders_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='checkout_url',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='description',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='email',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_items',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='payment_title',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='response_dump',
        ),
        migrations.AddField(
            model_name='orders',
            name='orderuniqueId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='total',
            field=models.DecimalField(decimal_places=2, default=777, max_digits=8),
            preserve_default=False,
        ),
    ]
