# Generated by Django 4.2.6 on 2023-10-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_remove_orders_amount_remove_orders_checkout_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_items',
            field=models.ManyToManyField(blank=True, related_name='order_items', to='mainapp.orderitems'),
        ),
    ]
