# Generated by Django 4.2.6 on 2023-10-08 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_orders_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_items',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='total',
        ),
    ]
